### ISSUE TITLE
Usage for 10X datasets

### ISSUE THREAD

**Issue by Nusob888** [pachterlab/LSCHWCP_2023#1]
Hi, 
Thank you for this great approach to viral transcript quantification. 

I am wondering if I might be able to clarify how one would run this on 10x datasets. I noted that you benchmarked this on a sea-well experiment and a parse biosciences combinatorial indexing dataset. 

For your example code, there is no assignment for barcode positions, so I presume for see-well and parse datasets, this is auto detected?

Should I just be following the kb-python tutorial and assigning 10x chemistries in the technology parameter? but substitute the index as you have shown in your code?

Many thanks in advance

**Comment by Nusob888** [comment]
Update, alignment was possible using kb-python tutorials using default settings for 10x data.

**Comment by gauravgadhvi** [comment]
Hi @Nusob888 , I am trying to use this approach for viral quantification on our 10xv3 datasets as well. 
When I align the data using the kallisto bus and subsequent commands as illustrated in the notebooks, I do get an almost empty "matrix.sample.barcodes" file, which I believe is used in the following QC section. 

Did you also face this issue with your 10x dataset? And if you did, how did you move forward with the QC part and quantifying the viral reads? 
Thank you for your help!
