### ISSUE TITLE
Query regarding multiple sample runs 

### ISSUE THREAD

**Issue by sxf-ux** [pachterlab/LSCHWCP_2023#2]
Hi. I had a question.

For my 10X fastq data, I have one SRR sample with multiple samples within it `(SRR1_S1, SRR1_S2, SRR1_S3, SRR_S4)`. Each has their own respective paired reads.

How would I format my input to account for this ? I would preferably want to treat it as one sample so aggregate all the forward and reverse reads as the input for fastq_1 and fastq_2 but if you have any ideas, that would be great.

Thank you in advance !

**Comment by lauraluebbert** [comment]
Hi Safiyah, 

Sorry for the late response. You can either loop over the files, align one at a time and then combine the resulting count matrices (as was done [here](https://github.com/pachterlab/LSCHWCP_2023/blob/main/Notebooks/Supp_Fig_9/Supp_Fig_9c/1_align_blank_reagent_libraries.ipynb))), or you can use the `--batch-barcodes` argument. Check out Box 7 of our [documentation paper](https://www.biorxiv.org/content/10.1101/2023.11.21.568164v2.full.pdf) to see how the `--batch-barcodes` argument works. I hope this helps!
